import type { Metadata } from "next";
import { Inter, Bodoni_Moda, Playfair_Display } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import CursorFollower from "@/components/CursorFollower";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const bodoniModa = Bodoni_Moda({
  variable: "--font-bodoni",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

// export const metadata: Metadata = {
//   title: "Erfan Aalam | Fullstack developer",
//   description: "Generated by create next app",
// };

const SITE_KEYWORDS = [
  "ErfanAalam",
  "Erfan Aalam",
  "Erfan",
  "Aalam",
  "qureshi",
  "erfanqureshi",
  "erfanaalam",
  "fullstack developer",
  "full stack developer",
  "app developer",
  "web developer",
  "freelance developer",
  "flutter developer",
  "react developer",
  "next.js developer",
  "typescript developer",
  "javascript developer",
  "frontend developer",
  "backend developer",
  "mobile app developer",
  "software engineer",
  "web development",
  "mobile development",
  "react native",
  "node.js",
  "portfolio",
  "developer portfolio",
  "freelance",
  "hire developer",
  "web applications",
  "mobile applications",
  "responsive design",
  "UI/UX developer",
  "full stack engineer",
  "software development",
  "programming",
  "coding",
  "tech portfolio",
];

export const metadata: Metadata = {
  title: "Erfan Aalam | Fullstack Developer & App Developer",
  description:
    "Portfolio of Erfan Aalam - Experienced Fullstack Developer specializing in web and mobile app development. Expert in React, Next.js, Flutter, and modern web technologies. Available for freelance projects.",
  icons: {
    icon: "/favicon/favicon.ico",
  },
  metadataBase: new URL("https://erfanaalam.in"),
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  twitter: {
    card: "summary_large_image",
    title: "Erfan Aalam | Fullstack Developer",
    description:
      "Portfolio of Erfan Aalam - Experienced Fullstack Developer specializing in web and mobile app development. Expert in React, Next.js, Flutter, and modern web technologies.",
    site: "@Efan",
    creator: "@Erfan Aalam",
  },
  keywords: SITE_KEYWORDS,
  creator: "Erfan Aalam",
  openGraph: {
    url: "https://erfanaalam.in",
    type: "website",
    title: "Erfan Aalam | Fullstack Developer & App Developer",
    siteName: "Erfan Aalam Portfolio",
    description:
      "Portfolio of Erfan Aalam - Experienced Fullstack Developer specializing in web and mobile app development. Expert in React, Next.js, Flutter, and modern web technologies. Available for freelance projects.",
    locale: "en-US",
    images: [
      {
        url: "/favicon/favicon.ico",
        width: 1200,
        height: 630,
        alt: "Erfan Aalam - Fullstack Developer Portfolio",
        type: "image/png",
      },
    ],
  },
  alternates: {
    canonical: "https://erfanaalam.in",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${bodoniModa.className} ${playfairDisplay.className} scroll-smooth font-sans antialiased bg-white dark:bg-black transition-colors`}
      >
        <Script
          id="theme-script"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('theme') || 
                    (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
                  if (theme === 'dark') {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
        {/* Structured Data (JSON-LD) for SEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Person",
              name: "Erfan Aalam",
              alternateName: ["ErfanAalam", "Erfan Qureshi"],
              url: "https://erfanaalam.in",
              image: "https://erfanaalam.in/favicon/favicon.ico",
              jobTitle: "Fullstack Developer",
              worksFor: {
                "@type": "Organization",
                name: "Freelance",
              },
              description:
                "Experienced Fullstack Developer specializing in web and mobile app development. Expert in React, Next.js, Flutter, and modern web technologies.",
              knowsAbout: [
                "Web Development",
                "Mobile App Development",
                "React",
                "Next.js",
                "Node.js",
                "Flutter",
                "TypeScript",
                "JavaScript",
                "PostgreSQL",
                "Full Stack Development",
              ],
              sameAs: [
                "https://github.com/ErfanAalam",
                "https://www.linkedin.com/in/erfanaalam/",
                "https://x.com/ErfanAalam03",
              ],
              alumniOf: {
                "@type": "Organization",
                name: "IT Company",
              },
            }),
          }}
        />
        <ThemeProvider>
          <CursorFollower />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
